//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVNNhaNam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donvivanchuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donvivanchuyen()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public string SdtDV { get; set; }
        public string DiachiDV { get; set; }
        public string EmailDV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
