//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVNNhaNam
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
        }
    
        public string MaSP { get; set; }
        public string MaDM { get; set; }
        public string TenSP { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> KhoiluongSP { get; set; }
        public Nullable<double> Dongiaban { get; set; }
        public Nullable<int> SLTon { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
    }
}
